trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: nepeters.azure-blueprints.CreateBlueprint.CreateBlueprint@2
  displayName: 'Create Azure Blueprint'
  inputs:
    azureSubscription: 'nepeters-management-group'
    BlueprintName: 'blueprints-demo'
    BlueprintPath: './create/blueprint-body.json'
    ArtifactsPath: './create/artifacts'
    PublishBlueprint: true

steps:
- task: nepeters.azure-blueprints.AssignBlueprint.AssignBlueprint@2
  displayName: 'Assign Azure Blueprint'
  inputs:
    azureSubscription: 'nepeters-management-group'
    BlueprintName: 'blueprints-demo'
    ParametersFile: './assign/assign-blueprint.json'
    SubscriptionID: 'd5b9d4b7-6fc1-46c5-bafe-38effaed19b2'
