# trigger:
# - master

pool:
  vmImage: 'windows-2019'

steps:

- task: CreateBlueprint@1
  inputs:
    azureSubscription: 'nepeters-internal'
    BlueprintName: 'blueprints-demo'
    BlueprintPath: 'create'
    AlternateLocation: true
    AlternateSubscription: 3762d87c-ddb8-425f-b2fc-29e5e859edaf
    PublishBlueprint: true