# trigger:
# - master

pool:
  vmImage: 'windows-2019'

steps:

- task: CreateBlueprint@1
  inputs:
    azureSubscription: 'nepeters-internal-two'
    BlueprintName: 'test-assign-mg'
    BlueprintPath: 'create'
    AlternateLocation: false
    PublishBlueprint: true