trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:

- task: CreateBlueprint@1
  inputs:
    azureSubscription: 'nepeters-internal'
    BlueprintName: 'blueprints-demo'
    BlueprintPath: 'create'
    AlternateLocation: false
    PublishBlueprint: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'get-childitem'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $items = get-childitem
      
      foreach ($item in $item) {
        write-output $item 
      }