name: Hello World
on: [push, pull_request]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create Azure Blueprint
        env:
          AZURETENANTID: ${{ secrets.AZURETENANTID }}
          AZURECLIENTID: ${{ secrets.AZURECLIENTID }}
          AZUREPASSWORD: ${{ secrets.AZUREPASSWORD }}
        uses: neilpeterson/action-create-blueprint@master
        with:
          creationScope: Subscription
          azureSubscriptionID: 3762d87c-ddb8-425f-b2fc-29e5e859edaf
          blueprintName: actionBlueprintPublish002
          blueprintPath: ./create
          publishBlueprint: false

      # - name: Assign Azure Blueprint
      #   env:
      #     AZURETENANTID: ${{ secrets.AZURETENANTID }}
      #     AZURECLIENTID: ${{ secrets.AZURECLIENTID }}
      #     AZUREPASSWORD: ${{ secrets.AZUREPASSWORD }}
      #   uses: neilpeterson/azure-blueprint-actions/assign-blueprint@master
      #   with:
      #     AssignmentName: actionBlueprintPublish
      #     azureManagementGroupName: nepeters-internal
      #     blueprintName: actionBlueprintPublish
      #     azureSubscriptionID: 3762d87c-ddb8-425f-b2fc-29e5e859edaf
      #     AssignmentFilePath: ./assign/assign-blueprint.json

