name: Hello World
on: [push, pull_request]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Sample Container Action
        env:
          AZURETENANTID: ${{ secrets.AZURETENANTID }}
          AZURECLIENTID: ${{ secrets.AZURECLIENTID }}
          AZUREPASSWORD: ${{ secrets.AZUREPASSWORD }}
        uses: neilpeterson/my-first-github-action/create-blueprint@master
        with:
          azureManagementGroupName: nepeters-internal
          blueprintName: actionTest2
          blueprintPath: ./create/blueprint.json
