name: Hello World
on: [push, pull_request]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Sample Container Action
        env:
          INPUT_AZURESERVICEPRINCIPALID: ${{ secrets.INPUT_AZURESERVICEPRINCIPALID }}
          INPUT_AZURESERVICEPRINCIPALPASSWORD: ${{ secrets.INPUT_AZURESERVICEPRINCIPALPASSWORD }}
          INPUT_AZURETENANTID: ${{ secrets.INPUT_AZURETENANTID }}
        uses: neilpeterson/my-first-github-action/create-blueprint@master
        with:
          azureManagementGroupName: nepeters-internal2
          blueprintName: actionTest
          blueprintPath: ./create/blueprint.json