name: Hello World
on: [push, pull_request]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ls ./create
      - name: Create Azure Blueprint
        env:
          AZURETENANTID: ${{ secrets.AZURETENANTID }}
          AZURECLIENTID: ${{ secrets.AZURECLIENTID }}
          AZUREPASSWORD: ${{ secrets.AZUREPASSWORD }}
        uses: neilpeterson/azure-blueprint-actions/create-blueprint@master
        with:
          azureManagementGroupName: nepeters-internal
          blueprintName: actionTest001
          blueprintPath: create/
