name: Hello World
on: [push, pull_request]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create Azure Blueprint
        env:
          AZURETENANTID: ${{ secrets.AZURETENANTID }}
          AZURECLIENTID: ${{ secrets.AZURECLIENTID }}
          AZUREPASSWORD: ${{ secrets.AZUREPASSWORD }}
        uses: neilpeterson/action-create-blueprint@master
        with:
          azureManagementGroupName: nepeters-internal
          azureSubscriptionID: 3762d87c-ddb8-425f-b2fc-29e5e859edaf
          blueprintName: actionBlueprintPublish004
          blueprintPath: ./create
          version: v1

      - name: Assign Azure Blueprint
        env:
          AZURETENANTID: ${{ secrets.AZURETENANTID }}
          AZURECLIENTID: ${{ secrets.AZURECLIENTID }}
          AZUREPASSWORD: ${{ secrets.AZUREPASSWORD }}
        uses: neilpeterson/action-assign-blueprint@master
        with:
          AssignmentName: actionBlueprintPublish
          azureManagementGroupName: nepeters-internal
          blueprintName: actionBlueprintPublish004
          azureSubscriptionID: 3762d87c-ddb8-425f-b2fc-29e5e859edaf
          AssignmentFilePath: ./assign/assign-blueprint.json

