name: Hello World
on: [push, pull_request]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Sample Container Action
        uses: neilpeterson/my-first-github-action/create-blueprint@master
        with:
          blueprintName: actionTest
          blueprintPath: ./create/blueprint.json
