name: Hello World
on: [push, pull_request]

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create Azure Blueprint
        env:
          AZURETENANTID: ${{ secrets.AZURETENANTID }}
          AZURECLIENTID: ${{ secrets.AZURECLIENTID }}
          AZUREPASSWORD: ${{ secrets.AZUREPASSWORD }}
        uses: neilpeterson/action-create-blueprint@master
        with:
          scope: Subscription
          azureSubscriptionID: 3762d87c-ddb8-425f-b2fc-29e5e859edaf
          blueprintName: actionBlueprintPublish900
          blueprintPath: ./create
          version: increment

      - name: Assign Azure Blueprint 2
        env:
          AZURETENANTID: ${{ secrets.AZURETENANTID }}
          AZURECLIENTID: ${{ secrets.AZURECLIENTID }}
          AZUREPASSWORD: ${{ secrets.AZUREPASSWORD }}
        uses: neilpeterson/action-assign-blueprint@master
        with:
          scope: subscription
          azureSubscriptionID: 3762d87c-ddb8-425f-b2fc-29e5e859edaf
          assignmentName: actionBlueprintPublish900
          blueprintName: actionBlueprintPublish900
          AssignmentFilePath: ./assign/assign-blueprint.json

